Customer journeys API implementation
VingtCinq/python-mailchimp pull request #245
Opened 2022-11-03 16:57 UTC by ollz272

Noticed this bit of documentation in the mailchimp API that isn't supported by this package.

https://mailchimp.com/developer/marketing/api/customer-journeys-journeys-steps-actions/

Should be fairly self explanatory

2022-11-21 10:17 UTC, ollz272 commented
@stephenross hows this looking?

2022-11-21 14:52 UTC, stephenross requested changes
Some info shuffling in a couple files. Also, please update the README.rst file as well with the information you put in the .md file using that set of formatting as well. Sorry for the delay in checking this, but the endpoint itself looks good.

2022-11-21 14:52 UTC, stephenross commented on mailchimp3/__init__.py
> +from mailchimp3.entities.customerjourney import CustomerJourney
Formatting: This import needs to go right above the comment about E-Commerce and needs a comment above it about Customer Journeys. The imports here are listed in the order the API Documentation lists them and we would like to maintain that.

2022-11-21 14:52 UTC, stephenross commented on mailchimp3/__init__.py
> +        self.journeys = self.customer_journeys = CustomerJourney(self)
Formatting: This block belongs above near 142 right above the E-Commerce comment, see the other note at the top of this file for the why.

2023-04-15 20:56 UTC, ollz272 commented
> # Customer Journey
>         self.journeys = self.customer_journeys = CustomerJourney(self)

Thanks @stephenross, sorry for the long wait here, i haven't been working with this package much recently. I've updated the code as requested.

2023-04-15 21:46 UTC, stephenross approved these changes
Looks good to me.

2023-04-15 21:46 UTC, merged

2023-04-15 21:48 UTC, stephenross commented
@charlesthk Would you kindly push this to PyPi. I just noticed the image block at the top of the README files was not name bumped for the new version, but setup.py did get bumped properly.

2023-04-17 07:08 UTC, charlesthk commented
@stephenross @ollz272 thanks for this PR, new version is on PyPi.